ALTER TABLE forms ADD COLUMN IF NOT EXISTS theme JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS header_image TEXT;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS logo_image TEXT;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS background_image TEXT;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS welcome_message TEXT;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS submit_button_text TEXT NOT NULL DEFAULT 'Enviar';
ALTER TABLE forms ADD COLUMN IF NOT EXISTS success_message TEXT;

CREATE INDEX IF NOT EXISTS idx_form_theme ON forms USING GIN (theme);
